# Generated by Django 4.2.16 on 2024-11-13 13:46

import bookshelf.book.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Not more than 490 characters and first letter should be upper', validators=[django.core.validators.MaxLengthValidator(490), bookshelf.book.validators.UpperValueValidator]),
        ),
    ]
