# Generated by Django 4.2.16 on 2024-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Classics', 'Classics'), ('Crime', 'Crime'), ('Thriller', 'Thriller'), ('Sports', 'Sports'), ('Biography', 'Biography'), ('Fiction', 'Fiction'), ('Science', 'Science'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Business', 'Business'), ('Psychology', 'Psychology'), ('Nonfiction', 'Nonfiction'), ('Others', 'Others')], default='Others', max_length=40),
        ),
    ]
