# Generated by Django 4.2.16 on 2024-11-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbookstatus',
            options={'verbose_name': 'User Book Status', 'verbose_name_plural': 'User Book Statuses'},
        ),
    ]
