# Generated by Django 4.2.16 on 2024-11-16 22:49

import bookshelf.author.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(validators=[bookshelf.author.validators.UpperValueValidator(message='Biography must start with an uppercase letter.')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, validators=[bookshelf.author.validators.UpperValueValidator]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, validators=[bookshelf.author.validators.UpperValueValidator]),
        ),
    ]
