# Generated by Django 4.2.16 on 2024-11-16 23:27

import bookshelf.author.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_bio_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, validators=[bookshelf.author.validators.UpperValueValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, validators=[bookshelf.author.validators.UpperValueValidator()]),
        ),
    ]
