# Generated by Django 4.2.16 on 2024-11-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('Amateur', 'Amateur'), ('Semi-Pro', 'Semi-Pro'), ('Pro', 'Pro'), ('World-Class', 'World-Class'), ('King of the book knowledges', 'King of the book knowledges')], editable=False, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
